apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-deployment
  labels:
    app: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
        - name: php-apache
          image: php:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: html-volume
              mountPath: /var/www/html
          # Liveness Probe: Ensure PHP is running
          livenessProbe:
            httpGet:
              path: /index.php  # Or a custom script
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          # Readiness Probe: Check if the app is ready to handle traffic
          readinessProbe:
            httpGet:
              path: /index.php  # Or a custom script
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
      volumes:
        - name: html-volume
          configMap:
            name: php-apache-config
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache-service
spec:
  selector:
    app: php-apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-apache-config
data:
  index.php: |
    <?php
      echo "Hello from PHP Apache!";
    ?>