apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
        - name: cluster-autoscaler
          image: "k8s.gcr.io/cluster-autoscaler:v1.22.0"
          command:
            - ./cluster-autoscaler
            - --v=4
            - --namespace=kube-system
            - --nodes=1:10:spot-node-group
            - --scale-down-delay-explicitly-set-by-user=10m
            - --scale-down-utilization-threshold=0.5
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --balance-similar-node-groups=true
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
            requests:
              memory: 100Mi
              cpu: 50m
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: aws-region
                  key: region