AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'eks.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'EKSExecutionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'eks:*'
                  - 'cloudformation:*'
                  - 'iam:PassRole'
                  - 's3:GetObject'
                Resource: "*"

  EKSClusterRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'eks.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'EKSClusterPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:DescribeSubnets'
                Resource: "*"

  EKSClusterAutoScalerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'eks.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'EKSClusterAutoScalerPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'autoscaling:DescribeAutoScalingGroups'
                  - 'autoscaling:DescribeAutoScalingInstances'
                  - 'autoscaling:DescribeLaunchConfigurations'
                  - 'autoscaling:DescribeTags'
                  - 'autoscaling:SetDesiredCapacity'
                  - 'autoscaling:TerminateInstanceInAutoScalingGroup'
                Resource: 
                  Fn::Sub: arn:aws:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*:autoScalingGroupName/*
              - Effect: 'Allow'
                Action:
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeLaunchTemplateVersions'
                  - 'ec2:DescribeRegions'
                Resource: "*"

Outputs:
  ExecutionRoleArn:
    Description: "Execution Role ARN"
    Value: !GetAtt ExecutionRole.Arn 

  EKSClusterRoleArn:
    Description: "EKS Cluster Role ARN"
    Value: !GetAtt EKSClusterRole.Arn 

  EKSClusterAutoScalerRoleArn:
    Description: "EKS AutoScaler Role ARN"
    Value: !GetAtt EKSClusterAutoScalerRole.Arn  